<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CI74CGQ" failures="1" tests="11" name="com.qa.crm.tests.HomePageTest" time="3.544" errors="0" timestamp="2025-04-12T17:39:05 IST" skipped="5">
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageTitleTest" time="0.039"/>
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="isHomePageIconTest" time="2.735"/>
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="isCalendarPageIconTest" time="0.047"/>
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="isContactsPageIconTest" time="0.046"/>
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageHeadersCountTest" time="0.066">
    <skipped/>
  </testcase> <!-- homePageHeadersCountTest -->
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageHeadersCountTest" time="0.084">
    <skipped/>
  </testcase> <!-- homePageHeadersCountTest -->
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageHeadersCountTest" time="0.087">
    <skipped/>
  </testcase> <!-- homePageHeadersCountTest -->
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageHeadersCountTest" time="0.105">
    <failure message="expected [3] but found [5]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [3] but found [5]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.qa.crm.tests.HomePageTest.homePageHeadersCountTest(HomePageTest.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- homePageHeadersCountTest -->
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageHeadersTest" time="0.116">
    <skipped/>
  </testcase> <!-- homePageHeadersTest -->
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageHeadersTest" time="0.159">
    <skipped/>
  </testcase> <!-- homePageHeadersTest -->
  <system-out/>
  <testcase classname="com.qa.crm.tests.HomePageTest" name="homePageHeadersTest" time="0.060"/>
  <system-out/>
</testsuite> <!-- com.qa.crm.tests.HomePageTest -->
